### ISSUE TITLE
Can't open or share URL in version 2.13

### ISSUE THREAD

**Issue by eengnr** [TrianguloY/UrlChecker#281]
### Steps to reproduce

Hi, thanks for your app!
In version 2.13 the URLChecker overlay just disappears when I tap "Open with (any browser)" or the "Share" button. It's not possible to open the checked URL.
This is not an issue in 2.12, that's why I downgraded.

### Expected behavior

Browser or share menu should be opened after tapping it in URLChecker.

### Actual behavior

URLChecker just disappears.

### URLCheck version

2.13

### Android version

Android 14

### Android Custom/Specific ROM or Device

Stock Pixel 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by TrianguloY** [comment]
The first version 2.13 (code 27) had a bug with the share option, that was fixed silently on a second 2.13 version (code 28).

Can you upgrade again and check if sharing works now?

As for opening in browser...that's odd. Does it happens with all browsers? Any in particular? All urls? I cannot reproduce it on my device nor an emulator, can you provide a specific url/browser (anything) where it happens?

**Comment by eengnr** [comment]
F-Droid seems to only provide the broken version and most likely won't build again as long as no 2.14 is released. I.e. the share issue still exists there.

I can confirm that share works in the Play Store version. But opening with a browser does not work, either.
I just try to share the URL of this issue from Fennec/Chrome/Cromite -> URLCheck -> Fennec/Chrome/Cromite and URLCheck just disappears.

**Comment by TrianguloY** [comment]
According to the Fdroid logs the new version was built yesterday, maybe it will be available in a couple days.

As for the opening bug, I cannot reproduce it like you say on my device (Android 13) but will try on an android 14 emulator. Sorry for the inconvenience

**Comment by arquiem** [comment]
I was going to create a ticked but this has been reported so I will post here. I'm also having problems with 2.13, albeit minor ones. Links call for Firefox / incognito correctly but for some reason I can't open YouTube in NewPipe and vice versa.
Further testing showed that these two apps were solely responsible for this behaviour, I called YouTube from Tumblr and it worked fine. 
Copying the yt link and checking from the clipboard show the same problem, it doesn't open.
Downgraded to 2.12 as this problem didn't show up there.
Tried 2.13(28) but the problem remained there. 
Tested on Android 12 (a21sub)

**Comment by TrianguloY** [comment]
For those of you where it doesn't work. Could someone try this workaround? 

1. Enable the flags editor module (you can move it under the drawer to hide it from view)
2. Search for ACTIVITY_NEW_TASK and press the left flag icon until it is filled. See picture below
3. Save and exit

Does it work now? 

![Screenshot_20231016-083219.png](https://github.com/TrianguloY/UrlChecker/assets/10616202/ef9c73e5-efa0-478e-ac31-ee104ec8e248)

**Comment by eengnr** [comment]
> For those of you where it doesn't work. Could someone try this workaround?
> 
>     1. Enable the flags editor module (you can move it under the drawer to hide it from view)
> 
>     2. Search for ACTIVITY_NEW_TASK and press the left flag icon until it is filled. See picture below
> 
>     3. Save and exit
> 
> 
> Does it work now?
> 
> ![Screenshot_20231016-083219.png](https://user-images.githubusercontent.com/10616202/275412213-ef9c73e5-efa0-478e-ac31-ee104ec8e248.png)

Yes, this works for me! Thank you!!

**Comment by arquiem** [comment]
Yes, this workaround works for me. Tried (28) and play store versions and both solved the situations I mentioned, thanks.

**Comment by TrianguloY** [comment]
Perfect, thanks for checking! 
Now I need to find a proper solution...

That workaround will make all apps opened as new tasks. Not an issue in most cases, but since this app should act as an "invisible" middleware, if an app requests to maintain the original task, I want to at least try to do so.

**Comment by Blocked** [comment]
@TrianguloY  Not sure if related, but share => share doesn't work, open => share works. To be clear, Share from App1=>Open with UrlCheck => Share button doesn't work. Maybe related to #92

**Comment by modularanne** [comment]
Confirming bug on 2.13 (28) and 2.13 (26) from f-droid. 
Pinned 2.12 for now.

**Comment by TrianguloY** [comment]
Version 2.13.1 is (finally) available on both play store and f-droid.
It should hopefully fix the issue.

However, if it didn't and you still have the bug, just reopen this issue and I'll take another look, no problem.

Also, if you configured the flags module with the workaround, it's better to reset it (or disable the module itself).
